import { StyleSheet } from 'react-native';
import { Spacing, BorderRadius, Theme } from '@/constants/theme';

export const createStyles = (theme: Theme) => {
  return StyleSheet.create({
    loadingContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      padding: Spacing.xl,
    },
    loadingText: {
      marginTop: Spacing.md,
    },
    scrollContainer: {
      flexGrow: 1,
      padding: Spacing.xl,
    },
    header: {
      padding: Spacing.xl,
      borderRadius: BorderRadius['2xl'],
      marginBottom: Spacing.xl,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.08,
      shadowRadius: 12,
      elevation: 8,
    },
    headerTop: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: Spacing.lg,
    },
    userInfo: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    avatar: {
      width: 52,
      height: 52,
      borderRadius: 26,
      justifyContent: 'center',
      alignItems: 'center',
      marginRight: Spacing.md,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 4,
    },
    headerActions: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.sm,
    },
    iconButton: {
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: theme.backgroundTertiary,
      justifyContent: 'center',
      alignItems: 'center',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.05,
      shadowRadius: 4,
      elevation: 2,
    },
    todaySection: {
      marginTop: Spacing.lg,
    },
    mealButtons: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      gap: Spacing.md,
      marginTop: Spacing.xl,
    },
    mealButton: {
      flex: 1,
      paddingVertical: Spacing.xl,
      paddingHorizontal: Spacing.md,
      borderRadius: BorderRadius['2xl'],
      alignItems: 'center',
      minHeight: 100,
      justifyContent: 'center',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.08,
      shadowRadius: 8,
      elevation: 4,
    },
    mealButtonText: {
      marginTop: Spacing.md,
    },
    remindersSection: {
      marginBottom: Spacing.xl,
    },
    remindersScrollContainer: {
      maxHeight: 160,
    },
    reminderItem: {
      flexDirection: 'row',
      alignItems: 'center',
      padding: Spacing.lg,
      backgroundColor: theme.backgroundTertiary,
      borderRadius: BorderRadius.xl,
      marginBottom: Spacing.sm,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.06,
      shadowRadius: 8,
      elevation: 3,
    },
    reminderIconContainer: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: 'rgba(239, 68, 68, 0.1)',
      justifyContent: 'center',
      alignItems: 'center',
      marginRight: Spacing.lg,
    },
    reminderContent: {
      flex: 1,
    },
    relationshipsSection: {
      marginBottom: Spacing.xl,
      padding: Spacing.xl,
      borderRadius: BorderRadius['2xl'],
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.08,
      shadowRadius: 12,
      elevation: 8,
    },
    emptyState: {
      alignItems: 'center',
      paddingVertical: Spacing['4xl'],
    },
    emptyText: {
      marginTop: Spacing.lg,
      textAlign: 'center',
    },
    relationshipItem: {
      padding: Spacing.xl,
      borderRadius: BorderRadius.xl,
      marginBottom: Spacing.lg,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.06,
      shadowRadius: 8,
      elevation: 3,
    },
    relationshipUserInfo: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: Spacing.lg,
    },
    userName: {
      fontSize: 18,
      fontWeight: '700',
    },
    userOriginalName: {
      fontSize: 14,
      marginTop: 4,
    },
    statusText: {
      marginTop: 4,
    },
    relationshipUserTextContainer: {
      flex: 1,
    },
    relationshipActions: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: Spacing.md,
    },
    reminderSettingsButton: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: Spacing.md,
      paddingVertical: Spacing.sm,
      borderRadius: BorderRadius.lg,
      backgroundColor: 'rgba(236, 72, 153, 0.1)',
      gap: Spacing.xs,
      minWidth: 90,
      justifyContent: 'center',
    },
    reminderSettingsText: {
      fontWeight: '600',
    },
    miniMealButtons: {
      flex: 1,
      flexDirection: 'row',
      gap: Spacing.sm,
    },
    miniMealButton: {
      flex: 1,
      paddingVertical: Spacing.md,
      paddingHorizontal: Spacing.sm,
      borderRadius: BorderRadius.lg,
      alignItems: 'center',
      minHeight: 60,
      justifyContent: 'center',
    },
    miniMealButtonText: {
      marginTop: 4,
      fontSize: 12,
      fontWeight: '500',
    },
    inputGroup: {
      marginBottom: Spacing.xl,
    },
    searchInputContainer: {
      flexDirection: 'row',
      gap: Spacing.md,
      alignItems: 'center',
    },
    searchInput: {
      flex: 1,
      backgroundColor: theme.backgroundTertiary,
      borderRadius: BorderRadius.xl,
      padding: Spacing.lg,
      paddingHorizontal: Spacing.xl,
      fontSize: 16,
      borderWidth: 0,
    },
    searchButton: {
      width: 52,
      height: 52,
      borderRadius: BorderRadius.xl,
      justifyContent: 'center',
      alignItems: 'center',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 4,
    },
    searchResult: {
      flexDirection: 'row',
      alignItems: 'center',
      padding: Spacing.lg,
      borderRadius: BorderRadius.xl,
      marginTop: Spacing.lg,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.06,
      shadowRadius: 8,
      elevation: 3,
    },
    searchResultInfo: {
      flex: 1,
      marginLeft: Spacing.lg,
    },
    dateText: {
      marginTop: Spacing.md,
    },
    settingsButton: {
      padding: Spacing.sm,
    },
    section: {
      padding: Spacing.xl,
      borderRadius: BorderRadius['2xl'],
      marginBottom: Spacing.xl,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.08,
      shadowRadius: 12,
      elevation: 8,
    },
    sectionTitle: {
      marginBottom: Spacing.lg,
    },
    sectionHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: Spacing.lg,
    },
    mealsContainer: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      gap: Spacing.md,
    },
    mealCard: {
      flex: 1,
      padding: Spacing.xl,
      borderRadius: BorderRadius.xl,
      alignItems: 'center',
      minHeight: 120,
      justifyContent: 'center',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.08,
      shadowRadius: 8,
      elevation: 4,
    },
    mealLabel: {
      marginTop: Spacing.md,
      marginBottom: Spacing.md,
    },
    checkIcon: {
      position: 'absolute',
      top: Spacing.md,
      right: Spacing.md,
    },
    checkButton: {
      marginTop: Spacing.md,
      padding: Spacing.sm,
      borderRadius: BorderRadius.lg,
      minWidth: 50,
      alignItems: 'center',
    },
    addButton: {
      padding: Spacing.sm,
    },
    emptyContainer: {
      alignItems: 'center',
      paddingVertical: Spacing['4xl'],
    },
    reminderText: {
      marginLeft: Spacing.md,
      flex: 1,
    },
    relationshipCard: {
      padding: Spacing.xl,
      borderRadius: BorderRadius.xl,
      marginBottom: Spacing.lg,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.06,
      shadowRadius: 8,
      elevation: 3,
    },
    relationshipHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: Spacing.lg,
    },
    pinkAlert: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: Spacing.md,
      paddingVertical: Spacing.sm,
      borderRadius: BorderRadius.lg,
    },
    alertText: {
      marginLeft: Spacing.sm,
      fontWeight: '500',
    },
    mealsStatusContainer: {
      flexDirection: 'row',
      justifyContent: 'space-between',
    },
    mealStatusItem: {
      flexDirection: 'column',
      alignItems: 'center',
      flex: 1,
    },
    remindButton: {
      marginTop: Spacing.sm,
      padding: Spacing.sm,
      borderRadius: BorderRadius.lg,
      minWidth: 50,
      alignItems: 'center',
      justifyContent: 'center',
    },
    logoutButton: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      padding: Spacing.lg,
      marginTop: Spacing.xl,
      borderRadius: BorderRadius.xl,
    },
    modalOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0, 0, 0, 0.4)',
      justifyContent: 'center',
      alignItems: 'center',
      padding: Spacing.xl,
    },
    modalContent: {
      width: '100%',
      maxWidth: 420,
      borderRadius: BorderRadius['3xl'],
      padding: 0,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.12,
      shadowRadius: 24,
      elevation: 16,
    },
    modalHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      padding: Spacing.xl,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: theme.border,
    },
    modalBody: {
      padding: Spacing.xl,
    },
    inputLabel: {
      marginBottom: Spacing.sm,
      marginTop: Spacing.lg,
    },
    input: {
      backgroundColor: theme.backgroundTertiary,
      borderRadius: BorderRadius.xl,
      padding: Spacing.lg,
      paddingHorizontal: Spacing.xl,
      fontSize: 16,
      borderWidth: 0,
    },
    modalFooter: {
      flexDirection: 'row',
      padding: Spacing.xl,
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: theme.border,
      gap: Spacing.md,
    },
    modalButton: {
      flex: 1,
      paddingVertical: Spacing.lg,
      borderRadius: BorderRadius.xl,
      alignItems: 'center',
      fontWeight: '600',
    },
  });
};
