import { StyleSheet } from 'react-native';
import { Spacing, BorderRadius, Theme } from '@/constants/theme';

export const createStyles = (theme: Theme) => {
  return StyleSheet.create({
    container: {
      flex: 1,
      paddingHorizontal: Spacing.xl,
      paddingTop: Spacing['3xl'],
      paddingBottom: Spacing.xl,
    },
    header: {
      marginBottom: Spacing['4xl'],
      alignItems: 'center',
    },
    headerIcon: {
      width: 90,
      height: 90,
      borderRadius: 45,
      backgroundColor: `${theme.primary}15`,
      justifyContent: 'center',
      alignItems: 'center',
      marginBottom: Spacing.xl,
      shadowColor: theme.primary,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.2,
      shadowRadius: 12,
      elevation: 8,
    },
    form: {
      gap: Spacing.xl,
      marginBottom: Spacing['4xl'],
    },
    inputContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: Spacing.xl,
      paddingVertical: Spacing.xl,
      borderRadius: BorderRadius.xl,
      gap: Spacing.md,
      borderWidth: 0,
      backgroundColor: theme.backgroundTertiary,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.06,
      shadowRadius: 8,
      elevation: 3,
    },
    inputIcon: {
      width: 24,
      textAlign: 'center',
    },
    inputWrapper: {
      flex: 1,
    },
    textInput: {
      marginTop: 6,
      padding: 0,
      minHeight: 26,
      fontSize: 16,
      fontWeight: '500',
    },
    buttons: {
      flexDirection: 'row',
      gap: Spacing.lg,
      marginTop: 'auto',
    },
    button: {
      flex: 1,
      paddingVertical: Spacing.xl,
      paddingHorizontal: Spacing['2xl'],
      borderRadius: BorderRadius.xl,
      alignItems: 'center',
      justifyContent: 'center',
      height: 60,
      fontWeight: '600',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.1,
      shadowRadius: 8,
      elevation: 4,
    },
    cancelButton: {
      backgroundColor: theme.backgroundDefault,
      borderWidth: 0,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.06,
      shadowRadius: 8,
      elevation: 3,
    },
    backButton: {
      position: 'absolute',
      top: Spacing['3xl'],
      left: Spacing.lg,
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: theme.backgroundDefault,
      justifyContent: 'center',
      alignItems: 'center',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 6,
      elevation: 4,
      zIndex: 100,
    },
  });
};
